### PR TITLE
Fix DynamicForm - Taxonomy field

### LINKED ISSUE #1267: Bug: DynamicForm does not properly handle NULL default values for Taxonomy fields
Taxonomy fields (multi select or single select) with a NULL default value cause the form to fail loading, leaving the user only seeing the spinner and no error message.  Blank string default values are handled properly.

### PR DESCRIPTION
**Pull request by michaelmaillot**
| Q               | A
| --------------- | ---
| Bug fix?        | [x]
| New feature?    | [ ]
| New sample?      | [ ]
| Related issues?  | fixes #1267 & #1268

#### What's in this Pull Request?

- Fixing Taxonomy field when NULL / blank during update / load
- Fixing ControlsTest webpart to handle DynamicForm event examples
- Formatting ControlsTest Toggle components

### CODE REVIEW

**Comment by joelfmrodrigues** [comment]
@michaelmaillot many thanks for the PR! could you please resolve conflicts?

File: src/controls/dynamicForm/DynamicForm.tsx [hunk 1]
```diff
@@ -255,8 +255,8 @@ export class DynamicForm extends React.Component<
           } else if (fieldType === "TaxonomyFieldType") {
             objects[columnInternalName] = {
               __metadata: { type: "SP.Taxonomy.TaxonomyFieldValue" },
-              Label: value[0].name,
-              TermGuid: value[0].key,
+              Label: value[0]?.name ?? "",
+              TermGuid: value[0]?.key ?? "11111111-1111-1111-1111-111111111111",
               WssId: "-1",
```
Comment (joelfmrodrigues) [inline src/controls/dynamicForm/DynamicForm.tsx:260]: Test comment

**Comment by joelfmrodrigues** [comment]
@michaelmaillot many thanks, this is now merged
