### PR TITLE
🐛 - Fix 1655- Dynamic form should not display any validation errors until the user clicks Save/Submit, or leaves the focus of a required control - (Repo Rescuer Challenge)

### LINKED ISSUE #1655: Dynamic Form Loads with Validation Errors if no List Item Id is set
[ ] Enhancement

[X ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.15.0]

#### Expected / Desired Behavior / Question
When loading a Dynamic Form with no list item id (new item), the form should not display any validation errors until the user clicks Save/Submit, or leaves the focus of a required control.

#### Observed Behavior
When loading a Dynamic Form with no list item id (new item) all of the required fields display validation errors by default.

#### Steps to Reproduce
Create A Dynamic Form with no list item id set, and link it to a list that has a required field.  You will see the errors load by default.

You can see this error reported by @sallaadithya in a sub comment for an existing bug here: https://github.com/pnp/sp-dev-fx-controls-react/issues/1586#issuecomment-1637459697

### PR DESCRIPTION
**Pull request by NishkalankBezawada**
| Q               | A
| --------------- | ---
| Bug fix?        | [x]
| New feature?    | [ ]
| New sample?      | [ ]
| Related issues?  | fixes #1655 

#### What's in this Pull Request?
Fixing issue #1655 

#### Observation
When loading a Dynamic Form with no list item id (new item), the form should not display any validation errors until the user clicks Save/Submit, or leaves the focus of a required control.

#### Actual behavior
When loading a Dynamic Form with no list item id (new item) all of the required fields display validation errors by default.

#### Solution
In ```DynamicField.tsx``` component, individual field is set and the validation is done through the methods ```getRequiredErrorText()``` and ```getNumberErrorText()```

These methods currently are only checking with ```changedValue``` property, which will be always empty for a new item. An additional check is done on basis of ```listItemId``` assuming that the fact that for new item, this will be empty, we can achieve to not to show the validation errors on the form. 

#### Observed 

Issue1655

#### After change

Issue1615

#### Edit scenario

Issue1655-Edit

Thanks,
Nish

### CODE REVIEW

File: src/controls/dynamicForm/dynamicField/IDynamicFieldState.ts [hunk 1]
```diff
@@ -3,4 +3,5 @@ export interface IDynamicFieldState {
   * The options available to the listPicker
   */
   changedValue: any; // eslint-disable-line @typescript-eslint/no-explicit-any
+  listItemId:any; // eslint-disable-line @typescript-eslint/no-explicit-any
```
Comment (AJIXuMuK) [inline src/controls/dynamicForm/dynamicField/IDynamicFieldState.ts:6]: Why do you need `listItemId` in `state`? Couldn't you just use it from `props`?

**Review by AJIXuMuK — CHANGES_REQUESTED** [review]

File: src/controls/dynamicForm/dynamicField/IDynamicFieldState.ts (hunk 1 above)
Comment (NishkalankBezawada) [reply src/controls/dynamicForm/dynamicField/IDynamicFieldState.ts]: My bad, missed that. Changed as suggested :). 

//Nish

**Review by AJIXuMuK — APPROVED** [review]

**Comment by AJIXuMuK** [comment]
Thank you @NishkalankBezawada for the change!
