### PR TITLE
Fix - Issue 1592 - Dynamic form - Number validations are working, but the percentage values are not getting saved

### LINKED ISSUE #1592: Dynamic Controls - Number validations on the Percentage column is working, but the value in the percentage column is not getting saved.
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.15.0 Beta version]

#### Expected / Desired Behavior / Question
Entering the value between 1 to 100 into percentage column should save the form. 

#### Observed Behavior
The number validations are working like a charm, but if we are using a percentage column and trying to save the value to that column, it is not saving the values. Below is the screen for the validations

image

#### Steps to Reproduce
1) Add field Number and choose as 'Show as percentage'
2) Use this list in Dynamic form, with New Item, and give the value as 15 and click save

The form will not be saved. 

#### Observations
The properties number field if chosen as 'Shown as percentage', the minimum and maximum values will be retrieved as below, 

image

wherein, the properties of number field without choosing 'Show as percentage', the minimum and maximum values will be retrieved as below. 

image

And at ```onSubmitClick```, the validation for percentage column is failing due to the minimum and maximum values for the percentage column. 

image

Thanks,
Nishkalank Bezawada

### PR DESCRIPTION
**Pull request by NishkalankBezawada**
| Q               | A
| --------------- | ---
| Bug fix?        | [x]
| New feature?    | [ ]
| New sample?      | [ ]
| Related issues?  | fixes #1592 

#### What's in this Pull Request?
Fix for issue #1592 

#### Problem
The number validations are working like a charm, but if we are using a percentage column and trying to save the value to that column, it is not saving the values. Below is the screen for the validations

image

#### Steps to Reproduce
1) Add field Number and choose as 'Show as percentage'
2) Use this list in Dynamic form, with New Item, and give the value as 15 and click save
The form will not be saved. 

#### Solution
The properties number field if chosen as 'Shown as percentage', the minimum and maximum values will be retrieved as below, 

image

wherein, the properties of number field without choosing 'Show as percentage', the minimum and maximum values will be retrieved as below. 

image

And at ```onSubmitClick```, the validation for percentage column is failing due to the minimum and maximum values for the percentage column. 

image

While validating a number, the percentage column is validated as below, 
image

While ```onSubmit``` the same validation for the percentage column is not done, instead, the minimum value and maximum value is checked with the default values as 0.1 and 1 respectively. 

So, a new method is introduced to check the validation again while the user is submitting the form as below, 
image

Thanks,
Nishkalank

### CODE REVIEW

File: src/controls/dynamicForm/DynamicForm.tsx [hunk 1]
```diff
@@ -840,4 +843,20 @@ export class DynamicForm extends React.Component<
 
     return errorMessage;
   };
+
+  private validateNumberOnSubmit = (val:IDynamicFieldProps): boolean => {
+    let shouldBeReturnBack = false;
+    if (val.fieldType === "Number" && val.showAsPercentage) {
+      let minValue = val.minimumValue !== undefined ? val.minimumValue * 100 : undefined;
```
Comment (michaelmaillot) [inline src/controls/dynamicForm/DynamicForm.tsx:850]: Please declare this as `const` since it's not reassigned in the function.

File: src/controls/dynamicForm/DynamicForm.tsx [hunk 2]
```diff
@@ -840,4 +843,20 @@ export class DynamicForm extends React.Component<
...
+      let maxValue = val.maximumValue !== undefined ? val.maximumValue * 100 : undefined;
```
Comment (michaelmaillot) [inline src/controls/dynamicForm/DynamicForm.tsx:851]: Please declare this as `const` since it's not reassigned in the function.

**Comment by michaelmaillot** [comment]
Hi @NishkalankBezawada,

Thanks for this fix!

I've requested a few little things to update, can you have a look at them?

**Comment by NishkalankBezawada** [comment]
> Hi @NishkalankBezawada,
> 
> 
> 
> Thanks for this fix!
> 
> 
> 
> I've requested a few little things to update, can you have a look at them?

Hey @michaelmaillot 

Sure thing, I'll do it early tomorrow in the morning 😊

Thanks for the review.
Nishkalank

**Comment by michaelmaillot** [comment]
Merged manually.

Thank you @NishkalankBezawada!

**Comment by NishkalankBezawada** [comment]
> Merged manually.
> 
> 
> 
> Thank you @NishkalankBezawada!

Thanks a lot @michaelmaillot
