### PR TITLE
ListItemAttachments Control - fixing the OnClick handler when clicking on the document card

### LINKED ISSUE #1541: ListItemAttachment OnClick open wrong URL
#### Category
[ ] Enhancement

[x ] Bug

[ ] Question

3.14.0 Version

Please specify what version of the library you are using: [  3.14.0  ]

#### Bug Found
When trying to open a file on the ListItemAttachments control, the URL contains duplicate parameters between the absolute url and the serverRelativeURL 
Resulting URL:  
https://TENANT.sharepoint.com/sites/SITE/_layouts/15//sites/SITE/Lists/LISTNAME/Attachments/ID/FILENAME.msg?web=1

/sites/SITE duplicated on the URL also and extra /

#### Steps to Reproduce
Use the ListItemAttachments control
Add a bunch of files with names like
File # 1.msg
File # 2.xml
File # 3.docx
Try to download any file using ListItemAttachments control

### PR DESCRIPTION
**Pull request by NishkalankBezawada**
| Q               | A
| --------------- | ---
| Bug fix?        | [x ]
| New feature?    | [ ]
| New sample?      | [ ]
| Related issues?  | fixes #1541 

#### Problem statement
In the earlier version, When trying to open a file on the ListItemAttachments control, the URL contains duplicate parameters between the absolute url and the serverRelativeURL as below
Result URL:
https://TENANT.sharepoint.com/sites/SITE/_layouts/15//sites/SITE/Lists/LISTNAME/Attachments/ID/FILENAME.msg?web=1

#### Solution
The problem is caused in the OnClick handler of DocumentCard, while parsing the URL using ```encodeURIComponent``` (As below)

```Typescript
 onClickHref={!openAttachmentsInNewWindow && `${encodeURIComponent(file.ServerRelativeUrl)}?web=1`}
onClick={openAttachmentsInNewWindow && (() => window.open(`${encodeURIComponent(file.ServerRelativeUrl)}?web=1`, "_blank"))}
```
Screen shot of the old code
image

 By removing this, was able to make it work again.
```Typescript
onClickHref={!openAttachmentsInNewWindow && `${(file.ServerRelativeUrl)}?web=1`} 
onClick={openAttachmentsInNewWindow && (() => window.open(`${(file.ServerRelativeUrl)}?web=1`, "_blank"))} 
```
Screen shot of the corrected code
image

hence making the url be like `https://TENANT.sharepoint.com/sites/site/Lists/LISTNAME/Attachments/ID/FILENAME.msg?web=1`

Thanks,
Nishkalank

### CODE REVIEW

File: src/controls/listItemAttachments/ListItemAttachments.tsx [hunk 1]
```diff
@@ -274,8 +274,8 @@ export class ListItemAttachments extends React.Component<IListItemAttachmentsPro
                     directionalHint={DirectionalHint.rightCenter}>
 
                     <DocumentCard
-                      onClickHref={!openAttachmentsInNewWindow && `${encodeURIComponent(file.ServerRelativeUrl)}?web=1`}
-                      onClick={openAttachmentsInNewWindow && (() => window.open(`${encodeURIComponent(file.ServerRelativeUrl)}?web=1`, "_blank"))} // JJ - 20200613 - needed to support Microsoft Teams
+                      onClickHref={!openAttachmentsInNewWindow && `${(file.ServerRelativeUrl)}?web=1`} //NB - 20230607 - Fix for issue 1541
```
Comment (joelfmrodrigues) [inline src/controls/listItemAttachments/ListItemAttachments.tsx:277]: @NishkalankBezawada no need to add comments as this is not a generally adopted practice within the repository so I will remove them after the merge

**Comment by joelfmrodrigues** [comment]
@NishkalankBezawada many thanks for the fix, I tested this and it was working well.
I have also tracked down when the `encodeURIComponent` was introduced and found this was related to #1484. I tested uploading a file with the `#` character in the name and the character was removed, and opening the file worked as expected. I have also tried adding that file as an attachment via SharePoint UI and there was an error message saying that the character was invalid. Seems to me that SharePoint internal validation is now taking care of the special character and this is no longer an issue, so your PR does not seem to introduce #1484 again. All good :)

(Never thought I had to test so many things for a PR that only removed a function to encode a string 😆)

**Comment by NishkalankBezawada** [comment]
Many thanks @joelfmrodrigues  for the merge and your insightful comments. 

I also saw that SharePoint handles validation; therefore, I removed the `encodeURIComponent` from the code to test, and it worked. I hope this is a long-lasting solution. 

Thanks,
Nishkalank
