### PR TITLE
Hotfix for 1937 and 1961

### LINKED ISSUE #1937: [Dynamic Form] Cannot Clean Up Date Field and Save it
### Category
[ ] Enhancement
[X] Bug
[ ] Question

### Version
3.20.0

### Problem Detail
I want to clean up the date field in **Dynamic Form** to set value to null.
By default, Dynamic Form doesn't support text input on date field, you need overwrite this field and enable **_allowTextInput_** property on `DatePicker` control so you can type/clean the date on it

Image

It worked at least one year ago.

Recently my team found that they cannot clean up date and it will throw error like` Cannot read properties of null (reading 'toString')`

Image

The root casue is on `OnChange` method in [DynamicForm,tsx](https://github.com/pnp/sp-dev-fx-controls-react/blob/master/src/controls/dynamicForm/DynamicForm.tsx)

Image

However, if I modify the code from

` field.stringValue = newValue.toString();`

to
` field.stringValue = newValue?.toString();`

I still cannot save my cleanup, because its **newValue** is **null** and **Dynamic Form** will only add fields whose newValue is not null/undefined into changes.  So my cleanup on date fields will never be submitted.

Image

I will debug the Dynamic Form control deeply to understand the logic of this code.

### Steps to Reproduce

1. Make sure your list contains date field
2. Override this date field in Dynamic Form to make sure the **DateTimePicker** enabled `allowTextInput`  property
3. Test your form customizer with an existing list item and try to clean up this date field
4. You should get the same error as I got.

### PR DESCRIPTION
**Pull request by wuxiaojun514**
| Q               | A
| --------------- | ---
| Bug fix?        | [x]
| New feature?    | [ ]
| New sample?      | [ ]
| Related issues?  | fixes #1937 and #1961

#### What's in this Pull Request?

This PR will fix the following issues:
1. #1937 Cannot clean up date field issue, and will enable `allowTextInput` property in date field control

2. #1961 Get exception when clean up a multiple lookup field

### CODE REVIEW

File: src/controls/dynamicForm/DynamicForm.tsx [hunk 1]
```diff
@@ -459,7 +459,7 @@ export class DynamicFormBase extends React.Component<
         if (fieldcolumnInternalName.startsWith('_x') || fieldcolumnInternalName.startsWith('_')) {
           fieldcolumnInternalName = `OData_${fieldcolumnInternalName}`;
         }
-        if (field.newValue !== null && field.newValue !== undefined) {
+        if (field.newValue !== undefined) {
```
Comment (AJIXuMuK) [inline src/controls/dynamicForm/DynamicForm.tsx:462]: hey @wuxiaojun514 - why are you removing the `null` check? what is the problem it causes?

Comment (wuxiaojun514) [reply src/controls/dynamicForm/DynamicForm.tsx:462]: Hi @AJIXuMuK ,
Thanks for the review.
This is due to this check will cause #1937 . Since the value of cleaned date field is null, this check will stop adding cleaned date field into changes. Then the clean up of date will not be saved.
You can see my previous comment at https://github.com/pnp/sp-dev-fx-controls-react/issues/1937#issuecomment-2608720195 for more information

**Comment by michaelmaillot** [comment]
Merged manually, thank you!
